# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='entity_message.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x65ntity_message.proto\"6\n\rEntityMessage\x12\x12\n\nmethodName\x18\x01 \x02(\t\x12\x11\n\tparamDict\x18\x02 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENTITYMESSAGE = _descriptor.Descriptor(
  name='EntityMessage',
  full_name='EntityMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='methodName', full_name='EntityMessage.methodName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='paramDict', full_name='EntityMessage.paramDict', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['EntityMessage'] = _ENTITYMESSAGE

EntityMessage = _reflection.GeneratedProtocolMessageType('EntityMessage', (_message.Message,), dict(
  DESCRIPTOR = _ENTITYMESSAGE,
  __module__ = 'entity_message_pb2'
  # @@protoc_insertion_point(class_scope:EntityMessage)
  ))
_sym_db.RegisterMessage(EntityMessage)


# @@protoc_insertion_point(module_scope)
